#!/bin/bash

echo "=== Accessing Stand Up Sydney Dev Server from Remote ==="
echo ""
echo "Your dev server is running on port 8082 on the droplet."
echo "Here are your options to access it:"
echo ""
echo "OPTION 1: SSH Tunnel (Recommended)"
echo "From your LOCAL computer, run:"
echo ""
echo "ssh -L 8082:localhost:8082 root@170.64.252.55"
echo ""
echo "Then open: http://localhost:8082 in your browser"
echo ""
echo "----------------------------------------"
echo ""
echo "OPTION 2: Expose to Network (Less Secure)"
echo "Modify the dev server to listen on all interfaces:"
echo ""
echo "npm run dev -- --host 0.0.0.0"
echo ""
echo "Then access: http://170.64.252.55:8082"
echo "(Make sure port 8082 is open in your firewall)"
echo ""
echo "----------------------------------------"
echo ""
echo "OPTION 3: Use Nginx Proxy (Production-like)"
echo "Set up Nginx to proxy to your dev server"
echo ""
echo "----------------------------------------"
echo ""
echo "Current server status:"
echo "Dev server: http://localhost:8082"
echo "Public IP: 170.64.252.55"