# Railway Nixpacks Configuration
# Explicit configuration for Stand Up Sydney dev preview

[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install]
cmds = ["npm ci --only=production=false"]

[phases.build]
cmds = [
  "chmod +x start-dev.sh",
  "echo 'Build phase complete - ready for dev server'"
]

[start]
cmd = "./start-dev.sh"
