[build]
builder = "DOCKERFILE"
dockerfilePath = "cloud-dev/Dockerfile"

[deploy]
numReplicas = 1
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[deploy.healthcheck]]
path = "/"
port = 8080
initialDelaySeconds = 30
periodSeconds = 10

[environments.production.variables]
# Set these in Railway dashboard
# VITE_SUPABASE_URL = "your-supabase-url"
# VITE_SUPABASE_ANON_KEY = "your-supabase-key"
# GITHUB_TOKEN = "your-github-token"
# NOTION_TOKEN = "your-notion-token"
# METRICOOL_API_KEY = "your-metricool-key"
# PASSWORD = "your-vscode-password"

[environments.production.deploy]
numReplicas = 1

# Expose ports for different services
[[services]]
name = "vscode"
port = 8080
protocol = "HTTP"

[[services]]
name = "dev-server"
port = 3000
protocol = "HTTP"

[[services]]
name = "mcp-gateway"
port = 8000
protocol = "HTTP"