# Railway Configuration

# CDE Service (uses Dockerfile.railway)
[deploy]
buildCommand = "echo 'CDE service - using Dockerfile'"
healthcheckPath = "/"

# Override for dev-preview service specifically
[environments.production.services.dev-preview]
buildCommand = "npm install"
startCommand = "npm run dev -- --host 0.0.0.0 --port $PORT"
