# Railway Multi-Service Configuration
# Two separate services with different build methods

# Default configuration for dev-preview service (Node.js/Vite)
[deploy]
buildCommand = "npm install"
startCommand = "npm run dev -- --host 0.0.0.0 --port $PORT"
healthcheckPath = "/"

# Service-specific configurations
[environments.production.services.dev-preview]
buildCommand = "npm install"
startCommand = "npm run dev -- --host 0.0.0.0 --port $PORT"
rootDirectory = "."

# CDE service configuration (uses Docker in cloud-dev directory)
[environments.production.services.claude-cde]
buildCommand = "echo 'Building CDE with Docker from cloud-dev directory'"
dockerfilePath = "cloud-dev/Dockerfile"
rootDirectory = "cloud-dev"
healthcheckPath = "/"
