[build]
dockerfilePath = "Dockerfile.railway"

[deploy]
numReplicas = 1
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[deploy.healthcheck]]
path = "/"
port = 3000
initialDelaySeconds = 90
periodSeconds = 20
